[package]
name = "cccost"
version = "0.1.0"
edition = "2024"

[dependencies]
tabled = {version = "0.20", features = ["ansi", "derive"]}
rayon = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }